/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-06 06:44:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class comment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1623371898000L));
    _jspx_dependants.put("jar:file:/Users/macbook/git/team/yeowoori/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/macbook/git/team/yeowoori/WebContent/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("  \n");
      out.write("  \n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>comment</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<style>\n");
      out.write("     \n");
      out.write("        .user-profile{\n");
      out.write("            width: 20px; height: 20px;\n");
      out.write("            border: 1px solid gainsboro;\n");
      out.write("            border-radius: 100px;\n");
      out.write("            background-repeat: no-repeat;\n");
      out.write("            background-size: cover;\n");
      out.write("            display: inline-block;\n");
      out.write("            vertical-align:middle;\n");
      out.write("       }\n");
      out.write("        .user-profile-big{\n");
      out.write("            width: 40px; height: 40px;\n");
      out.write("            border: 1px solid gainsboro;\n");
      out.write("            border-radius: 100px;\n");
      out.write("            background-repeat: no-repeat;\n");
      out.write("            background-size: cover;\n");
      out.write("            display: inline-block;\n");
      out.write("            vertical-align:middle;\n");
      out.write("            margin-right: 20px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("       }\n");
      out.write("       .user-name{\n");
      out.write("           width:fit-content;\n");
      out.write("           display: inline-block;\n");
      out.write("           font-size: 14px;\n");
      out.write("           margin-left: 0px;\n");
      out.write("           font-weight: 500;\n");
      out.write("       }\n");
      out.write("       .time{\n");
      out.write("           width:fit-content;\n");
      out.write("           display: inline-block;\n");
      out.write("           font-size: 12px;\n");
      out.write("           margin-left: 30px;\n");
      out.write("           font-weight: 300;\n");
      out.write("       }\n");
      out.write("      \n");
      out.write("       .comments{\n");
      out.write("        width:fit-content;\n");
      out.write("           display: inline-block;\n");
      out.write("           font-size: 12px;\n");
      out.write("           margin-right: 10px;\n");
      out.write("           font-weight: 400;\n");
      out.write("           color: grey;\n");
      out.write("       }\n");
      out.write("       .report{\n");
      out.write("            color: grey;\n");
      out.write("           font-size: 12px;\n");
      out.write("           margin-left: 10px;\n");
      out.write("           font-weight: 300;\n");
      out.write("           display: inline-block;\n");
      out.write("       }\n");
      out.write("       .text-container{\n");
      out.write("           display: inline-block;\n");
      out.write("           width: 80%; height: 35px;\n");
      out.write("           border : 1px solid rgb(192, 192, 192);\n");
      out.write("           border-radius: 5px;\n");
      out.write("\n");
      out.write("       }\n");
      out.write("       .input-comment{\n");
      out.write("           width: 85%; height: 32px;\n");
      out.write("           border: 0px;\n");
      out.write("           border-radius: 5px;\n");
      out.write("       }\n");
      out.write("       .btn-submit{\n");
      out.write("           background-color: white;\n");
      out.write("           border: 0px;\n");
      out.write("           padding: 0px;\n");
      out.write("           height: 5px;\n");
      out.write("           color: grey;\n");
      out.write("           font-weight: 500;\n");
      out.write("           float: right;\n");
      out.write("           margin-right: 10px;\n");
      out.write("           line-height: 2.3;\n");
      out.write("       }\n");
      out.write("       .btn-dh{\n");
      out.write("       		background-color : #eee;\n");
      out.write("       		border : 0px;\n");
      out.write("       		padding-left: 5px; padding-right:5px;\n");
      out.write("       		padding-top:3px; padding-bottom:3px;\n");
      out.write("       		font-size : 12px;\n");
      out.write("       		margin-right:10px;\n");
      out.write("       }\n");
      out.write("		.comment-content{\n");
      out.write("		display: inline-block; margin-left: 10px; font-size: 14px;\n");
      out.write("		}\n");
      out.write("		.CommentUpdateContent {\n");
      out.write("		   width: 80%; height: 32px;\n");
      out.write("           border: 1px solid grey;\n");
      out.write("           border-radius: 5px;\n");
      out.write("           resize:none;\n");
      out.write("		}\n");
      out.write("</style>\n");
      out.write("    \n");
      out.write("    <div class=\"container\">\n");
      out.write("      \n");
      out.write("   \n");
      out.write("      	<hr>\n");
      out.write("      	<div style=\"padding: 20px;\"></div>\n");
      out.write("        <h6>댓글 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.commentCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\n");
      out.write("        <div style=\"padding: 5px;\"></div>\n");
      out.write("         \n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        \n");
      out.write("     \n");
      out.write("        <div id=\"comment-list-area\">\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("       \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("    \n");
      out.write("    <form action=\"#\" method=\"POST\" name=\"requestForm\">\n");
      out.write("    	<input type=\"hidden\" name=\"boardNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("    	<input type=\"hidden\" name=\"cp\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.cp }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("    	<input type=\"hidden\" name=\"type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("    	<input type=\"hidden\" name=\"area\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.area }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("    </form>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("    	const loginMemberNo = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("    	const boardNo = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("    	let beforCommentRow;\n");
      out.write("    	\n");
      out.write("    	//댓글 등록\n");
      out.write("    	function addComment(){\n");
      out.write("    		const commentContent = $(\"#commentContent\").val();\n");
      out.write("    		if(commentContent.trim() ==\"\") {\n");
      out.write("    			swal(\"댓글 내용이 없습니다.\");\n");
      out.write("    		}else{\n");
      out.write("    			$.ajax({\n");
      out.write("    				url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/comment/insertComment\",\n");
      out.write("    				type : \"POST\",\n");
      out.write("    				data : {\"memberNo\" : loginMemberNo,\n");
      out.write("    						\"boardNo\" : boardNo,\n");
      out.write("    						\"commentContent\" : commentContent },\n");
      out.write("    				success : function(result){\n");
      out.write("    					if(result>0){\n");
      out.write("    						swal({\n");
      out.write("        						\"icon\" : \"success\",\n");
      out.write("        						\"title\" : \"댓글 등록 성공\"\n");
      out.write("        					})\n");
      out.write("        					$(\"#commentContent\").val(\"\");\n");
      out.write("    						selectCommentList();\n");
      out.write("    					}\n");
      out.write("    					\n");
      out.write("    				},\n");
      out.write("    				error : function(){\n");
      out.write("    					console.log(\"댓글 삽입 실패\");\n");
      out.write("    				}\n");
      out.write("    			})\n");
      out.write("    		}\n");
      out.write("    	}\n");
      out.write("    	\n");
      out.write("    	//댓글 조회\n");
      out.write("    	function selectCommentList(){\n");
      out.write(" 			\n");
      out.write("			$.ajax({\n");
      out.write("				url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/comment/list\",\n");
      out.write("				data : {\"boardNo\" : boardNo},\n");
      out.write("				type : \"POST\",\n");
      out.write("				dataType : \"JSON\", \n");
      out.write("				success : function(commentList){\n");
      out.write("					\n");
      out.write("			        $(\"#comment-list-area\").html(\"\");\n");
      out.write("			         \n");
      out.write("			        $.each(commentList, function(index, item){\n");
      out.write("					\n");
      out.write("			        	var div1 = $(\"<div>\").css(\"padding\", \"10px\");\n");
      out.write("			        	var div2 = $(\"<div>\").addClass(\"user-profile-big\").css(\"background-image\", \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+item.memberProfile+\")\");\n");
      out.write("			        	\n");
      out.write("			        	var div3 = $(\"<div>\").css(\"display\", \"inline-block\");\n");
      out.write("			        	\n");
      out.write("			        	var div31 = $(\"<div>\").addClass(\"user-name\").text(item.memberNickname);\n");
      out.write("			        	var div32 = $(\"<div>\").addClass(\"comment-content\").html(item.commentContent);\n");
      out.write("			        	var div33 = $(\"<div>\").addClass(\"ml-2\").css(\"position\", \"absolute\").css(\"right\", \"100px\");\n");
      out.write("			        	\n");
      out.write("			        	\n");
      out.write("			        	if(item.memberNo == loginMemberNo){\n");
      out.write("			        		   \n");
      out.write("				               var showUpdate = $(\"<button>\").addClass(\"btn btn-dh\").text(\"수정\").attr(\"onclick\", \"showUpdateComment(\"+item.commentNo+\", this)\");\n");
      out.write("				               var deleteComment = $(\"<button>\").addClass(\"btn btn-dh\").text(\"삭제\").attr(\"onclick\", \"deleteComment(\"+item.commentNo+\")\");\n");
      out.write("				               \n");
      out.write("				               div33.append(showUpdate).append(deleteComment);\n");
      out.write("				        }\n");
      out.write("\n");
      out.write("			        	div3.append(div31).append(div32).append(div33);\n");
      out.write("			        	\n");
      out.write("			        	var div4 = $(\"<div>\");\n");
      out.write("			        	\n");
      out.write("			        	var div41 = $(\"<div>\").addClass(\"time\").css(\"margin-left\", \"0px\").css(\"margin-right\", \"20px\").text(item.commentDate);\n");
      out.write("			        	\n");
      out.write("			        	var a42 = $(\"<a>\").prop(\"href\", \"#\");\n");
      out.write("			        	var img421 = $(\"<img>\").attr(\"src\", \"https://drive.google.com/uc?id=1e719tW6BVTrSPiZQIxJZ8LUWWuNsx0Lc\").css(\"height\", \"15px\");\n");
      out.write("			        	var div422 = $(\"<div>\").addClass(\"comments\").text(\"좋아요\");\n");
      out.write("			        	a42.append(img421).append(div422);\n");
      out.write("			        	\n");
      out.write("			        	var a43 = $(\"<a>\").prop(\"href\", \"#\").addClass(\"report\").text(\"신고\");\n");
      out.write("			        	\n");
      out.write("			        	div4.append(div41).append(a42).append(a43);\n");
      out.write("			        	\n");
      out.write("			        	div3.append(div4);\n");
      out.write("			        	\n");
      out.write("			            $(\"#comment-list-area\").append(div1).append(div2).append(div3);\n");
      out.write("			         }); \n");
      out.write("					\n");
      out.write("				},\n");
      out.write("				error : function(){\n");
      out.write("					console.log(\"댓글 목록 조회 실패\")\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("		}\n");
      out.write("    	\n");
      out.write("    	//댓글 수정 열리기\n");
      out.write("    	function showUpdateComment(commentNo, el){\n");
      out.write("    		\n");
      out.write("    		if($(\".replyUpdateContent\").length > 0){\n");
      out.write("    			$(\".replyUpdateContent\").eq(0).parent().html(beforeReplyRow);\n");
      out.write("    		}\n");
      out.write("    		\n");
      out.write("    		beforeReplyRow = $(el).parent().parent().html();\n");
      out.write("    		\n");
      out.write("    		var beforeContent = $(el).parent().prev().html();\n");
      out.write("    		\n");
      out.write("    		beforeContent = beforeContent.replace(/&amp;/g, \"&\");	\n");
      out.write("    		beforeContent = beforeContent.replace(/&lt;/g, \"<\");	\n");
      out.write("    		beforeContent = beforeContent.replace(/&gt;/g, \">\");	\n");
      out.write("    		beforeContent = beforeContent.replace(/&quot;/g, \"\\\"\");	\n");
      out.write("    		beforeContent = beforeContent.replace(/<br>/g, \"\\n\");	\n");
      out.write("    		\n");
      out.write("    		var textarea = $(\"<textarea>\").addClass(\"CommentUpdateContent\").val(beforeContent);\n");
      out.write("    		$(el).parent().parent().before(textarea);\n");
      out.write("    		$(el).parent().parent().remove();\n");
      out.write("    		\n");
      out.write("    		var updateBtn = $(\"<button>\").addClass(\"btn btn-dh\").text(\"댓글 수정\").attr(\"onclick\", \"updateComment(\" + replyNo + \", this)\");\n");
      out.write("    		var cancelBtn = $(\"<button>\").addClass(\"btn btn-dh\").text(\"취소\").attr(\"onclick\", \"updateCancel(this)\");\n");
      out.write("    		var div = $(\"<div>\").css(\"position\",\"absolute\").css(\"right\", \"100px\");\n");
      out.write("    		div.append(updateBtn).append(cancelBtn);\n");
      out.write("    		\n");
      out.write("    		$(el).parent().parent().append(div);		\n");
      out.write("    		\n");
      out.write("    		\n");
      out.write("    	}\n");
      out.write("    	\n");
      out.write("    	function updateCancel(el){\n");
      out.write("    		$(el).parent().parent().html( beforeReplyRow );\n");
      out.write("    		\n");
      out.write("    	}\n");
      out.write("\n");
      out.write("	//\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/comment.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/board/comment.jsp(5,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      // /WEB-INF/views/board/comment.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/comment.jsp(5,0) '${pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/comment.jsp(117,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginMember }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <div class=\"user-profile-big\" style=\"background-image: url(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberProfile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(");\"></div>\n");
          out.write("        <div class=\"text-container\">\n");
          out.write("            <input type=\"text\" class=\"input-comment\" id=\"commentContent\" name=\"commentContent\" placeholder=\"댓글을 입력해주세요.\">\n");
          out.write("            <button type=\"button\" class=\"btn-submit\" id=\"addComment\" onclick=\"addComment();\">등록</button>\n");
          out.write("        </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/board/comment.jsp(127,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty commentList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("        \n");
          out.write("     	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/board/comment.jsp(128,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/comment.jsp(128,8) '${commentList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${commentList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/comment.jsp(128,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("comment");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	        <div style=\"padding: 10px;\"></div>\n");
            out.write("	        <div class=\"user-profile-big\" style=\"background-image: url(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('/');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.memberProfile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\"></div>\n");
            out.write("	        <div style=\"display: inline-block;\">\n");
            out.write("	            <div class=\"user-name\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.memberNickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("	            <div class=\"comment-content\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentContent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("				\n");
            out.write("				");
            if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("				\n");
            out.write("				\n");
            out.write("	            <div>\n");
            out.write("	                <div class=\"time\" style=\"margin-left: 0px; margin-right: 20px;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("	                <a href=\"#\">\n");
            out.write("	                    <img src=\"https://drive.google.com/uc?id=1e719tW6BVTrSPiZQIxJZ8LUWWuNsx0Lc\" height=\"15px\">\n");
            out.write("	                    <div class=\"comments\">좋아요</div>\n");
            out.write("	                </a>\n");
            out.write("	                <a href=\"#\" class=\"report\">신고</a>\n");
            out.write("	\n");
            out.write("	            </div>\n");
            out.write("	            \n");
            out.write("	\n");
            out.write("	        </div>\n");
            out.write("	    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/board/comment.jsp(135,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo == comment.memberNo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				<div class=\"ml-2\" style=\"position:absolute; right:100px;\">\n");
          out.write("		             <button type=\"button\" class=\"btn btn-dh\" onclick=\"showUpdateComment(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(", this)\">수정</button>\n");
          out.write("		             <button type=\"button\" class=\"btn btn-dh\" onclick=\"deleteComment(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comment.commentNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">삭제</button>\n");
          out.write("	           	</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
